name: Lasr-Gpt4omini
class_name: LasrSearcher
api_type: "openai"
mode: "explicit"
api_model: "gpt-4o-mini"
api_url: "https://api.openai.com/v1"

num_iterations: 25
num_populations: 10
llm_weight: 0.001
early_stopping_condition: null
max_num_samples: 1000