name: Lasr-qwen3-8B-Instruct
class_name: LasrSearcher
api_type: "openai"
api_model: "Qwen/Qwen3-8B-Instruct"
api_url: ""

num_iterations: 25
num_populations: 10
llm_weight: 0.001
early_stopping_condition: null
max_num_samples: 2000