name: Llmsr-DeepInfra-Llama31_8b
class_name: LLMSRSearcher
api_type: "openai"
api_model: "meta-llama/Meta-Llama-3.1-8B-Instruct"
api_url: "https://api.deepinfra.com/v1/openai"
global_max_sample_num: 1000
samples_per_prompt: 4
functions_per_prompt: 4
num_samplers: 4
num_evaluators: 4
evaluate_timeout_seconds: 60
num_islands: 10