name: Llmsr-gpt4o-mini
class_name: LLMSRSearcher
api_type: "openai"
api_model: "gpt-4o-mini"
api_url: "https://api.openai.com/v1"
global_max_sample_num: 1000
samples_per_prompt: 4
functions_per_prompt: 4
num_samplers: 4
num_evaluators: 4
evaluate_timeout_seconds: 60
num_islands: 10